/*
 * This file is generated by jOOQ.
*/
package com.apress.demo.jooq.domain;


import com.apress.demo.jooq.domain.tables.Comments;
import com.apress.demo.jooq.domain.tables.Posts;
import com.apress.demo.jooq.domain.tables.records.CommentsRecord;
import com.apress.demo.jooq.domain.tables.records.PostsRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PostsRecord, Integer> IDENTITY_POSTS = Identities0.IDENTITY_POSTS;
    public static final Identity<CommentsRecord, Integer> IDENTITY_COMMENTS = Identities0.IDENTITY_COMMENTS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PostsRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
    public static final UniqueKey<CommentsRecord> CONSTRAINT_A = UniqueKeys0.CONSTRAINT_A;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CommentsRecord, PostsRecord> CONSTRAINT_AB = ForeignKeys0.CONSTRAINT_AB;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<PostsRecord, Integer> IDENTITY_POSTS = createIdentity(Posts.POSTS, Posts.POSTS.ID);
        public static Identity<CommentsRecord, Integer> IDENTITY_COMMENTS = createIdentity(Comments.COMMENTS, Comments.COMMENTS.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<PostsRecord> CONSTRAINT_4 = createUniqueKey(Posts.POSTS, "CONSTRAINT_4", Posts.POSTS.ID);
        public static final UniqueKey<CommentsRecord> CONSTRAINT_A = createUniqueKey(Comments.COMMENTS, "CONSTRAINT_A", Comments.COMMENTS.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<CommentsRecord, PostsRecord> CONSTRAINT_AB = createForeignKey(com.apress.demo.jooq.domain.Keys.CONSTRAINT_4, Comments.COMMENTS, "CONSTRAINT_AB", Comments.COMMENTS.POST_ID);
    }
}
