/*
 * This file is generated by jOOQ.
*/
package com.apress.demo.jooq.domain;


import com.apress.demo.jooq.domain.tables.Comments;
import com.apress.demo.jooq.domain.tables.Posts;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1955962765;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.POSTS</code>.
     */
    public final Posts POSTS = com.apress.demo.jooq.domain.tables.Posts.POSTS;

    /**
     * The table <code>PUBLIC.COMMENTS</code>.
     */
    public final Comments COMMENTS = com.apress.demo.jooq.domain.tables.Comments.COMMENTS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.SYSTEM_SEQUENCE_0558E38E_6B1D_43FA_B95C_34A85A5B6C82,
            Sequences.SYSTEM_SEQUENCE_8E42374F_16E6_47DC_87A8_BA6808C01C1C);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Posts.POSTS,
            Comments.COMMENTS);
    }
}
