/*
 * This file is generated by jOOQ.
*/
package com.apress.demo.jooq.domain;


import com.apress.demo.jooq.domain.tables.Comments;
import com.apress.demo.jooq.domain.tables.Posts;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.POSTS</code>.
     */
    public static final Posts POSTS = com.apress.demo.jooq.domain.tables.Posts.POSTS;

    /**
     * The table <code>PUBLIC.COMMENTS</code>.
     */
    public static final Comments COMMENTS = com.apress.demo.jooq.domain.tables.Comments.COMMENTS;
}
